---
Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    AnchorPeers: []

  - &AdminOrg
    Name: AdminOrg
    ID: AdminMSP
    MSPDir: crypto-config/peerOrganizations/admin.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('AdminMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('AdminMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('AdminMSP.admin')"
    AnchorPeers:
      - Host: peer0.admin.example.com
        Port: 8051

  - &FarmerOrg
    Name: FarmerOrg
    ID: FarmerMSP
    MSPDir: crypto-config/peerOrganizations/farmer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('FarmerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('FarmerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('FarmerMSP.admin')"
    AnchorPeers:
      - Host: peer0.farmer.example.com
        Port: 9051

  - &DistributorOrg
    Name: DistributorOrg
    ID: DistributorMSP
    MSPDir: crypto-config/peerOrganizations/distributor.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('DistributorMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('DistributorMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('DistributorMSP.admin')"
    AnchorPeers:
      - Host: peer0.distributor.example.com
        Port: 10051

  - &RetailerOrg
    Name: RetailerOrg
    ID: RetailerMSP
    MSPDir: crypto-config/peerOrganizations/retailer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RetailerMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('RetailerMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('RetailerMSP.admin')"
    AnchorPeers:
      - Host: peer0.retailer.example.com
        Port: 11051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.example.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
    - *OrdererOrg
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"

Profiles:
  OrdererGenesis:
    Orderer:
      <<: *OrdererDefaults
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      LettuceConsortium:
        Organizations:
          - *AdminOrg
          - *FarmerOrg
          - *DistributorOrg
          - *RetailerOrg
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"

  FarmerDistributorChannel:
    Consortium: LettuceConsortium
    Application:
      Organizations:
        - *AdminOrg
        - *FarmerOrg
        - *DistributorOrg
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Capabilities:
        <<: *ApplicationCapabilities
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"

  DistributorRetailerChannel:
    Consortium: LettuceConsortium
    Application:
      Organizations:
        - *AdminOrg
        - *DistributorOrg
        - *RetailerOrg
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Capabilities:
        <<: *ApplicationCapabilities
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"

  RetailerConsumerChannel:
    Consortium: LettuceConsortium
    Application:
      Organizations:
        - *AdminOrg
        - *RetailerOrg
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      Capabilities:
        <<: *ApplicationCapabilities
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
      Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
      Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
