networks:
  lettuce-scm-network:
  
volumes:
  couchdb-data-admin:
  couchdb-data-farmer:
  couchdb-data-distributor:
  couchdb-data-retailer:

services:
  # ------------------ OrdererOrg Ca -------------------
  ca-orderer:
    image: hyperledger/fabric-ca:latest
    container_name: ca-orderer
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-orderer
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_DEBUG=true
    ports:
      - "7054:7054"
    volumes:
      - ./ca-server/orderer:/etc/hyperledger/fabric-ca-server
    networks:
      - lettuce-scm-network
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    profiles: [ca]
    healthcheck:
      test: ["CMD", "sh", "-s", "sleep 10 && curl -f http://localhost:7054/cainfo"]       # health check for ca server, port is following container port
      interval: 10s
      timeout: 5s
      retries: 20

  # ------------------ AdminOrg Ca -------------------
  ca-admin:
    image: hyperledger/fabric-ca:latest
    container_name: ca-admin
    ports:
      # - "8054:7054"
      - "8054:8054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-admin
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./ca-server/admin:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - lettuce-scm-network
    profiles: [ca]
    healthcheck:
      test: ["CMD", "sh", "-s", "sleep 10 && curl -f http://localhost:8054/cainfo"]       # health check for ca server, port is following container port
      interval: 10s
      timeout: 5s
      retries: 20
  
  # ------------------ FarmerOrg Ca -------------------
  ca-farmer:
    image: hyperledger/fabric-ca:latest
    container_name: ca-farmer
    ports:
      # - "9054:7054"
      - "9054:9054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-farmer
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./ca-server/farmer:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - lettuce-scm-network
    profiles: [ca]
    healthcheck:
      test: ["CMD", "sh", "-s", "sleep 10 && curl -f http://localhost:9054/cainfo"]       # health check for ca server, port is following container port
      interval: 10s
      timeout: 5s
      retries: 20

  # ------------------ DistributorOrg Ca -------------------
  ca-distributor:
    image: hyperledger/fabric-ca:latest
    container_name: ca-distributor
    ports:
      # - "10054:7054"
      - "10054:10054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-distributor
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./ca-server/distributor:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - lettuce-scm-network
    profiles: [ca]
    healthcheck:
      test: ["CMD", "sh", "-s", "sleep 10 && curl -f http://localhost:10054/cainfo"]       # health check for ca server, port is following container port
      interval: 10s
      timeout: 5s
      retries: 20

  # ------------------ RetailerOrg Ca -------------------
  ca-retailer:
    image: hyperledger/fabric-ca:latest
    container_name: ca-retailer
    ports:
      # - "11054:7054"
      - "11054:11054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-retailer
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_DEBUG=true
    volumes:
      - ./ca-server/retailer:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    networks:
      - lettuce-scm-network
    profiles: [ca]
    healthcheck:
      test: ["CMD", "sh", "-s", "sleep 10 && curl -f http://localhost:11054/cainfo"]       # health check for ca server, port is following container port
      interval: 10s
      timeout: 5s
      retries: 20

  # ------------------ Orderer -------------------
  orderer.example.com:
    image: hyperledger/fabric-orderer:latest
    container_name: orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=DEBUG
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_ADMIN_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - "7050:7050"
    volumes:
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    networks:
      - lettuce-scm-network
    profiles: [peer]

  # ------------------ AdminOrg Peer -------------------
  peer0.admin.example.com:
    image: hyperledger/fabric-peer:latest
    container_name: peer0.admin
    depends_on:
      couchdb-admin:
        condition: service_healthy
    environment:
      - CORE_PEER_ID=peer0.admin.example.com
      - CORE_PEER_ADDRESS=peer0.admin.example.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.admin.example.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.admin.example.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.admin.example.com:8051
      - CORE_PEER_LOCALMSPID=AdminMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-admin:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/orderer-ca/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "8051:8051"
      - "8052:8052"
    volumes:
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/example.com/ca/ca-cert.pem:/etc/hyperledger/fabric/orderer-ca/ca.crt
      - ./crypto-config/peerOrganizations/admin.example.com/peers/peer0.admin.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/admin.example.com/users/Admin@admin.example.com/msp:/etc/hyperledger/peer/admin-msp
    networks:
      - lettuce-scm-network
    profiles: [peer]

  couchdb-admin:
    image: hyperledger/fabric-couchdb:latest
    container_name: couchdb-admin
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    volumes:
      - couchdb-data-admin:/opt/couchdb/data
    networks:
      - lettuce-scm-network
    profiles: [peer]
    healthcheck:
      test: ["CMD-SHELL", "echo 'Checking CouchDB via curl' && curl -s http://localhost:5984 | grep -q 'Welcome' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  # ------------------ FarmerOrg Peer -------------------
  peer0.farmer.example.com:
    image: hyperledger/fabric-peer:latest
    container_name: peer0.farmer
    depends_on:
      couchdb-farmer:
        condition: service_healthy
    environment:
      - CORE_PEER_ID=peer0.farmer.example.com
      - CORE_PEER_ADDRESS=peer0.farmer.example.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.farmer.example.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farmer.example.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.farmer.example.com:9051
      - CORE_PEER_LOCALMSPID=FarmerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-farmer:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/orderer-ca/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "9051:9051"
      - "9052:9052"
    volumes:
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/example.com/ca/ca-cert.pem:/etc/hyperledger/fabric/orderer-ca/ca.crt
      - ./crypto-config/peerOrganizations/farmer.example.com/peers/peer0.farmer.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/farmer.example.com/users/Admin@farmer.example.com/msp:/etc/hyperledger/peer/admin-msp
    networks:
      - lettuce-scm-network
    profiles: [peer]

  couchdb-farmer:
    image: hyperledger/fabric-couchdb:latest
    container_name: couchdb-farmer
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "6984:5984"
    volumes:
      - couchdb-data-farmer:/opt/couchdb/data
    networks:
      - lettuce-scm-network
    profiles: [peer]
    healthcheck:
      test: ["CMD-SHELL", "echo 'Checking CouchDB via curl' && curl -s http://localhost:5984 | grep -q 'Welcome' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  # ------------------ DistributorOrg Peer -------------------
  peer0.distributor.example.com:
    image: hyperledger/fabric-peer:latest
    container_name: peer0.distributor
    depends_on:
      couchdb-distributor:
        condition: service_healthy
    environment:
      - CORE_PEER_ID=peer0.distributor.example.com
      - CORE_PEER_ADDRESS=peer0.distributor.example.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.distributor.example.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.distributor.example.com:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.distributor.example.com:10051
      - CORE_PEER_LOCALMSPID=DistributorMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-distributor:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/orderer-ca/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "10051:10051"
      - "10052:10052"
    volumes:
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/example.com/ca/ca-cert.pem:/etc/hyperledger/fabric/orderer-ca/ca.crt
      - ./crypto-config/peerOrganizations/distributor.example.com/peers/peer0.distributor.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/distributor.example.com/users/Admin@distributor.example.com/msp:/etc/hyperledger/peer/admin-msp
    networks:
      - lettuce-scm-network
    profiles: [peer]

  couchdb-distributor:
    image: hyperledger/fabric-couchdb:latest
    container_name: couchdb-distributor
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "7984:5984"
    volumes:
      - couchdb-data-distributor:/opt/couchdb/data
    networks:
      - lettuce-scm-network
    profiles: [peer]
    healthcheck:
      test: ["CMD-SHELL", "echo 'Checking CouchDB via curl' && curl -s http://localhost:5984 | grep -q 'Welcome' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  # ------------------ RetailerOrg Peer -------------------
  peer0.retailer.example.com:
    image: hyperledger/fabric-peer:latest
    container_name: peer0.retailer
    depends_on:
      couchdb-retailer:
        condition: service_healthy
    environment:
      - CORE_PEER_ID=peer0.retailer.example.com
      - CORE_PEER_ADDRESS=peer0.retailer.example.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.retailer.example.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.retailer.example.com:11051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.retailer.example.com:11051
      - CORE_PEER_LOCALMSPID=RetailerMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb-retailer:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/orderer-ca/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "11051:11051"
      - "11052:11052"
    volumes:
      - ./channel-artifacts:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/example.com/ca/ca-cert.pem:/etc/hyperledger/fabric/orderer-ca/ca.crt
      - ./crypto-config/peerOrganizations/retailer.example.com/peers/peer0.retailer.example.com/msp:/etc/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/retailer.example.com/users/Admin@retailer.example.com/msp:/etc/hyperledger/peer/admin-msp
    networks:
      - lettuce-scm-network
    profiles: [peer]
    
  couchdb-retailer:
    image: hyperledger/fabric-couchdb:latest
    container_name: couchdb-retailer
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "8984:5984"
    volumes:
      - couchdb-data-retailer:/opt/couchdb/data
    networks:
      - lettuce-scm-network
    profiles: [peer]
    healthcheck:
      test: ["CMD-SHELL", "echo 'Checking CouchDB via curl' && curl -s http://localhost:5984 | grep -q 'Welcome' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
