NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca-<org>.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca-<org>.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca-<org>.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca-<org>.pem
    OrganizationalUnitIdentifier: orderer