# This file is for the Retailer Organization's CA
version: 1.5.7
port: 11054
debug: true
tls:
  enabled: false
  certfile:
  keyfile:
ca:
  name: ca-retailer
  keyfile:
  certfile:
crl:
  expiry: 24h
affiliations:
  retailer:
    - org1
registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: retailer.org1 # Affiliation for Retailer organization
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
db:
  type: sqlite3
  datasource: fabric-ca-server.db
intermediate:
  parentserver:
    url:
    CAName:
signing:
  default:
    usage:
      - digital signature
      - key encipherment
    expiry: 8760h
  profiles:
    tls:
      usage:
        - signing
        - key encipherment
        - server auth
        - client auth
      expiry: 8760h
      caconstraint:
        isca: false
        maxpathlen: -1